// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAd(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAd(ctx context.Context, id int64) (Ad, error)
	GetAdsByUserID(ctx context.Context, userID int64) ([]Ad, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListAds(ctx context.Context) ([]Ad, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAd(ctx context.Context, arg UpdateAdParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
